completing deposit
socious-io/socious-api-v3 pull request #11
Opened 2024-12-26 21:29 UTC by mohammadhb

2025-01-03 05:48 UTC, jeyem requested changes

2025-01-03 05:48 UTC, jeyem commented on src/apps/auth/middlewares.go
> +		identityUUID, err := utils.SafeUUIDParse(identityStr)
no need for creating new function to safe parse stuff : https://pkg.go.dev/github.com/google/uuid#Parse you can use this function instead it's convention for most of parsers you may safely parse with error return

2025-01-03 05:48 UTC, jeyem commented on src/apps/utils/utils.go
> +func SafeUUIDParse(input string) (u uuid.UUID, err error) {
this function is redundant

2025-01-05 23:02 UTC, mohammadhb commented
✅ Mentioned PR Changes is Done

2025-01-06 05:17 UTC, merged